---
title: "Link Nutrient and HPLC Data"
author: "Sebastian Di Geronimo"
date: 2026-09-24
format: html
editor: source
---

# 1.0 ---- Summary of Document ----



# 2.0 ---- Setup ----


## 2.1 Load Libraries

```{r setup, include=FALSE}
if (!nzchar(system.file(package = "librarian"))) 
  install.packages("librarian")

librarian::shelf(
  quiet = TRUE,
  librarian, conflicted, ggplot2, tibble, tidyr, readr, purrr, dplyr, stringr,
  forcats, lubridate, glue, fs, magrittr, here,
  
  # additional
  
)

conflicts_prefer(
  dplyr::filter(), 
  dplyr::select()
  )
  

```

## 2.2 Load Dataset

```{r load-zoo-cruise}
ecotaxa_path <- 
  here() %>%
  dir_ls(regexp = "export_summary_", recurse = TRUE)


zoo_cruise <- ecotaxa_path %>%
  read_tsv(show_col_types = FALSE) %>%
  distinct(sampleid) %>%
  separate_wider_delim(
    cols = sampleid,
    names = c("proj", "proj2", "cruise_id", "station", "mesh", "ecotaxa"),
    delim = "_",
    too_many = "drop"
  ) %>%
  mutate(
    .keep = "none",
    cruise_id = str_to_upper(cruise_id),
    station = str_to_upper(station),
    cruise_id = replace_values(
      cruise_id,
      "H23138" ~ "HG23138",
      "WS20230" ~ "WS20231",
      "WS20278" ~ "WS20279",
      "H23314" ~ "HG23314",
      "WS21277" ~ "WS21278"
      )
    )
zoo_cruise
```


```{r load-hplc}
hplc_path <- 
  here() %>%
  dir_ls(regexp = "hplc_consolidate", recurse = TRUE)

hplc_stn <- 
  read_csv(
    hplc_path, 
    show_col_types = FALSE, 
    na = c("", "NA", "-9999", "-8888"),
    name_repair = janitor::make_clean_names) %>%
  filter(str_detect(station, "MR|LK|WS")) %>%
  mutate(
    cruise_id = replace_values(
      cruise_id,
      "H23138" ~ "HG23138",
      "WS20230" ~ "WS20231",
      "WS20278" ~ "WS20279"
    ),
    date = str_remove(date, "T.*"),
    date = parse_date_time(date, orders = c("mdy", "ymd")),
    date = as_date(date),
    # replace na with 0
    across(tot_chl_a:last_col(), ~ replace_na(.x, 0)),
  ) %>%
  # average duplicate samples
  summarise(
    .by = c(cruise_id, station, depth),
    # metadata - take first row
    across(c(cruise, hplc_gsfc_id, sample, date, volfilt, water_depth, 
             date:lat, filters_replicates), 
           first),
    # average of data
    across(tot_chl_a:last_col(), ~ mean(.x, na.rm = TRUE)),
  ) %>%
  mutate(
    .by = c(cruise_id, station),
    .before = depth,
    depth_class = case_when(
      n() > 1  & depth == min(depth) ~ "Surface", 
      n() > 1  & depth == max(depth) ~ "Bottom", 
      n() == 1 & depth < 2 ~ "Surface",
      n() == 1 & depth > 2 ~ "Bottom",
      .default = "other"
    )
  ) %>%
  select(-c(cruise:filters_replicates))

hplc_stn
```




```{r load-nutrients}
noaa_bad <- c(
  "NA", "Under Review"
)

nutrients <- here() %>%
  dir_ls(regexp = "SFER_data", recurse = TRUE)

nut_filt <- 
  read_csv(nutrients, show_col_types = FALSE, na = noaa_bad) %>%
  filter(str_detect(station, "MR|LK|WS")) %>%
  mutate(station = if_else(str_detect(station, "LK"), "LK", station)) %>%
  arrange(datetime)
```




```{r}
nut_hplc <- 
  full_join(
    nut_filt,
    hplc_stn,
    by = join_by(cruise_id, station, depth_class)
  )

nut_hplc
```

```{r}
zoo_env <- 
  full_join(
    mutate(zoo_cruise, type2 = "zoo"),
    mutate(nut_hplc, type = "noaa") ,# %>%
    # distinct(cruise_id, station, type),
  ) %>%
  mutate(
    .after = 1,
    order = str_extract(cruise_id, "\\d.*")
  ) %>%
  mutate(
    .after = datetime, 
    date = as_date(datetime)
    ) %>%
  arrange(order)
  
zoo_env %>%
  filter(str_detect(cruise_id, "HG25083|SV18173|WS14335|WS15264|WS17212|WS19028|WS19210")) %>%
  nest(.by = cruise_id) %>%
  pull(data)
  count(cruise_id, station) %>%
  filter(n != 2)
  filter(is.na(type2)) %>%
  filter_out(is.na(type2)) %>%
  # filter_out(is.na(tot_chl_a)) %>%
  distinct(cruise_id, station)


```

HG25083	LK	4		
HG25083	MR	4		
HG25083	WS	4		
SV18173	LK	3		
WS14335	LK	1		
WS15264	LK	3		
WS17212	MR	3		
WS19028	WS	3		
WS19210	LK	3		
WS19210 WS  3

```{r}
integrate_profile <- function(depth, x) {
  ok <- !is.na(depth) & !is.na(x)

  if (sum(ok) < 2) {
    NA_real_
  } else {
    pracma::trapz(depth[ok], x[ok])
  }
}

zoo_env %>%
  arrange(cruise_id, station, depth.x) %>%
  summarise(
    .by = c(cruise_id, station, year:station_type),
    n_depths = n(),
    max_depth = max(depth.x, na.rm = TRUE),
    min_depth = min(depth.x, na.rm = TRUE),
    # max_chl = max(chl, na.rm = TRUE),
    # min_chl = min(chl, na.rm = TRUE),
    across(
      c(chl, pheo, nh4, po4, no3_no2, no3, no2, si),
      ~ integrate_profile(depth.x, .x),
      .names = "{.col}_integrated"
    )
  )

pracma::trapz((c(0, 31.6)), (c(0.708, 0.338)))
pracma::trapz( (c(0, 14, 31.6)), (c(0.708, 1, 0.338)))
```

```{r}
zoo_env %>%
      
  ggplot() +
  geom_path(
    aes(x = date, color = station, y = si), 
    na.rm = TRUE
  ) +
  geom_point(
    aes(x = date, color = station, y = si), 
    na.rm = TRUE
  ) +
  labs(
    title = "Silcate"
  ) +
  facet_grid(station~depth_order)

zoo_env %>%
      
  ggplot() +
  geom_path(
    aes(x = date, color = station, y = nh4), 
    na.rm = TRUE
  ) +
  geom_point(
    aes(x = date, color = station, y = nh4), 
    na.rm = TRUE
  ) +
    labs(
    title = "NH4"
  ) +
  facet_grid(station~depth_order)

zoo_env %>%
      
  ggplot() +
  geom_path(
    aes(x = date, color = station, y = no3_no2), 
    na.rm = TRUE
  ) +
  geom_point(
    aes(x = date, color = station, y = no3_no2), 
    na.rm = TRUE
  ) +
    labs(
    title = "NOx"
  ) +
  facet_grid(station~depth_order)

zoo_env %>%
  ggplot() +
  geom_path(
    aes(x = date, color = station, y = po4), 
    na.rm = TRUE
  ) +
  geom_point(
    aes(x = date, color = station, y = po4), 
    na.rm = TRUE
  ) +
    labs(
    title = "PO4"
  ) +
  facet_grid(station~depth_order)

zoo_env %>%
  mutate(
    # .keep = "used",
    # cruise_id, station, date,
    .after = no2_flag,
    no3_no2 = if_else(no3_no2 < 0.0001 | is.na(no3_no2), 0.0001, no3_no2),
    nh4 = if_else(nh4 < 0.0001 | is.na(nh4), 0.0001, nh4),
    po4 = if_else(po4 < 0.0001 | is.na(po4), NA, po4),
    # po42 = po4 < 0.0001 | is.na(po4),
    n_p_ratio = (no3_no2 + nh4) / po4,
    ) %>%
    # arrange(desc(ratio))
 ggplot() +
  geom_line(
    aes(x = date, color = station, y = n_p_ratio, group = station), 
    na.rm = TRUE
  ) +
  geom_point(
    aes(x = date, color = station, y = n_p_ratio), 
    na.rm = TRUE
  ) +
    labs(
    title = "N:P"
  ) +
  scale_y_continuous(limits = c(NA, 100),
                     oob = scales::oob_keep) +
  facet_grid(station~depth_order)
```

```{r}
(zoo_env %>%
  filter_out(is.na(tot_chl_a) | is.na(chl)) %>%
  ggplot() + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", colour = "grey") +
  geom_point(aes(x = tot_chl_a, y = chl, colour = cruise_id, group = station), 
             shape = 3, show.legend = FALSE) +
  facet_wrap(~year) +
  scale_x_continuous(limits = c(0, 1)) +
  scale_y_continuous(limits = c(0, 1)) +
  theme_bw() +
  theme(aspect.ratio = 1)) %>%
  plotly::ggplotly()
```

